language: node_js
node_js:
  - "lts/*"
  
branches:
  only:
    - main
    - master

install:
  - npm install yarn 

script:
  - yarn build

after_success:
  - echo "success!"

services:
  - docker

# passed: git push成功
# Broken: git push失败
# still failed: amend失败
# fixed: amend成功
